<?php

	/**
	 * Enumerations for the various data types existing in database world.
	 * @author demon
	 */
	final class CDFSqlDataType
	{
		/**
		 * String data type, up to a fixed size.
		 * @var int
		 */
		const String = 1;
		/**
		 * Integer data type.
		 * @var int
		 */
		const Integer = 2;
		/**
		 * Floating point number.
		 * @var int
		 */
		const Float = 3;
		/**
		 * Large amount of text (not a fixed size string)
		 * @var int
		 */
		const Text = 4;
		/**
		 * Timestamp, representing date and time in UTC format.
		 * @var int
		 */
		const Timestamp = 5;
		/**
		 * Boolean or bit.  True or false.
		 * @var int
		 */
		const Bool = 6;
	}

	const CDFIDataConnection_TokenCharacter = '?'; // must be one character

	/**
	 * Defines a common interface for manipulating database providers (such as MySQL).
	 * @author demon
	 */
	interface CDFIDataConnection
	{
		public function Open();
		public function Close();
		public function HasConnection();
		// clears down the connection object ready to accept a new query.
		public function NewQuery();
		// adds a parameter to use in a query or stored procedure call.
		public function AddParameter($type, $value);
		// executes the sql on the database.
		public function Query($sql);
		// executes a stored procedure on the database.
		public function Procedure($name);
		// returns last auto inserted value generated by previous query
		public function LastID();
	}

